spring:
  application:
    name: dispatch-manager-service

  cloud:
    config:
      import-check:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
          scope:
            - email

  kafka:
    producer:
      acks: 1
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: true
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.project.hems.*"

  rabbitmq:
    host: localhost
    port: 5672
    username: 
    password: 

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8091/eureka

server:
  port: 8084

property:
  config:
    kafka:
      dispatch-event-group-id: dispatch-event-readers
      dispatch-event-topic: ENERGY_DISPATCH_EVENTS
      dispatch-event-partition-count: 1

      dispatch-command-dlt-group-id: dispatch-command-dlt-readers
      dispatch-command-dlt-topic: ENERGY_DISPATCH_COMMANDS.DLT

      dispatch-command-group-id: dispatch-command-readers
      dispatch-command-topic: ENERGY_DISPATCH_COMMANDS
      dispatch-command-partition-count: 1

      vpp-service-group-id: vpp-requirement-group
      vpp-service-topic: VPP-REQUIREMENT
      vpp-service-partition-count: 3

      replica-count: 1

logging:
  level:
    com.project.hems.dispatch_manager_service: TRACE