spring:
  application:
    name: program-enrollment-manager

  datasource:
    url: not desclosed
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

