spring:
  application:
    name: program-enrollment-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/program_enrollment
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 

  config:
    import: optional:configserver:http://localhost:8095
server:
  port: 8089
