spring.application.name=ai-service

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8091/eureka/
server.port=9011

spring.ai.google.genai.api-key=AIzaSyD4xqmJU-rWIaIvQmsVm43eX8NO5S7Eq9Q
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

