spring:
  application:
    name: api-gateway-hems

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
          audiences:
            - https://api.mfa01.com
      client:
        registration:
          auth0:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - offline_access

        provider:
          auth0:
            issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: site-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/owner/**,/api/v1/site/**,/check-token-is-present/**

            - id: auth-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**

            - id: vpp-service-route
              uri: http://localhost:8086
              predicates:
                - Path=/vpp/**

            - id: program-enrollment-manager
              uri: http://localhost:8089
              predicates:
                - Path= /api/v1/program/**

            - id: email-service
              uri: http://localhost:8088
              predicates:
                - Path= /api/v1/mail/**,/api/**

            - id: dispatch-manager-service
              uri: http://localhost:8084
              predicates:
                - Path= /api/v1/dispatch/**

            - id: envoy-manager-service
              uri: http://localhost:8083
              predicates:
                - Path= /**

            - id: simulator-service
              uri: http://localhost:9010
              predicates:
                - Path= /api/v1/simulation/**

            - id: vpp-manager
              uri: http://localhost:8087
              predicates:
                - Path= /**


  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: Hems#Einfochips

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8091/eureka

server:
  port: 8090
  forward-headers-strategy: framework

auth0:
  domain:
  client-id:

  # mgmt-client-id:
  # mgmt-client-secret:
  # mgmt-audience: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/api/v2/

auth0-mgmt:
  client-id:
  client-secret: