spring:
  application:
    name: hems-chatbot-service

  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: 
        chat:
          options:
            model: gemini-2.5-flash

server:
  port: 8086