eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8091/eureka/

logging:
  level:
    '[com.netflix.eureka]': off
    '[com.netflix.discovery]': off

server:
  port: 8091
