spring:
  application:
    name: Email-Service
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail_quartz
    username: root
    password: Jills@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hems07293@gmail.com
    password: lhld nvzc ofui lukz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: Hems#Einfochips
    listener:
      simple:
        acknowledge-mode: manual

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry-hems:8761/eureka

server:
  port: 8088

