spring:
  application:
    name: Email-Service
  config:
    import: "optional:configserver:http://localhost:8095"


  #threadCount?? because if we have 3 schedule run at same time then we dont block so we use thread count 5
  #so each run on diff state so on time mail send successfully
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail_quartz
    username: root
    password: Jills@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info


hems:
  admin:
    deviceTokens:
      - "fzOkerNWxZ_cjm9izwYqyh:APA91bHzkzlKPKl29KE1l3Z1Z6WA1fp-9FjTE0u25AWxZwVvbYHwQX6rnBG1dNT9fz7fi6K4SodTvtx6Jj-TDI4SwqzrmROSMgBfA2AfUp6bWYGzalb7zOw"