spring:
  application:
    name: Email-Service
  config:
    import: "optional:configserver:http://localhost:8095"

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info